language: android
jdk: openjdk8
ppa: openjdk-r/ppa
os:
  - linux
android:
  components:
    - tools
    - build-tools-25
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-24

before_install:

before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check
  - ./gradlew assembleDebug assembleDebugAndroidTest
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck
  - ./gradlew connectedAndroidTest

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/